#!/bin/bash

echo "Connecting to remote kaniko shell.

Try sending:
executor --build-arg IAM_SSH_AGENT_VERSION=0.2.1 --no-push
"

set -x

exec docker run \
	--rm \
	-it \
	-v kanikoctl:/kanikoctl \
	alpine/socat \
		STDIO \
		unix-connect:/kanikoctl/socket
