#!/bin/bash

echo "Booting remote kaniko shell.

Depends on a docker volume called kanikoctl, create with:
docker volume create --label kanikoctl

Connect using script/client.
"

set -x

exec docker run \
	--rm \
	-it \
	-v $PWD:/workspace \
	-v kanikoctl:/kanikoctl \
	kaniko-socat \
		unix-listen:/kanikoctl/socket,fork \
		'exec:sh,stderr'
