#!/bin/bash

set -x

docker run \
	--rm \
	-it \
	--entrypoint /kaniko/socat \
	-v /Users/keithduncan/Projects/iam-ssh-agent/agent/:/workspace \
	-v kanikoctl:/kanikoctl \
	kaniko-socat \
		unix-listen:/kanikoctl/socket,fork \
		'exec:sh,stderr'
